version: '3'
services:
  samba:
    image: samba
    container_name: samba
    tty: true
    network_mode: bridge
    ports:
      - "445:445"
    build:
      context: .
      dockerfile: Dockerfile
